/*Ex 41*/
SELECT DISTINCT T.NOME, C.DESCRICAO AS CAMPEONATO
FROM TIME T
INNER JOIN TITULO L
ON L.IDTIME = T.ID
INNER JOIN CAMPEONATO C
ON L.IDCAMPEONATO = C.ID
WHERE C.DESCRICAO IN ('Mundial', 'Libertadores')

/*Ex 41 -- exemplo com subqueries*/
SELECT T.NOME
FROM TIME T
   INNER JOIN TITULO TT ON T.ID = TT.IDTIME
   INNER JOIN CAMPEONATO C ON TT.IDCAMPEONATO = C.ID
WHERE C.DESCRICAO = 'LIBERTADORES'
INTERSECT
SELECT T.NOME
FROM TIME T
   INNER JOIN TITULO TT ON T.ID = TT.IDTIME
   INNER JOIN CAMPEONATO C ON TT.IDCAMPEONATO = C.ID
WHERE C.DESCRICAO = 'MUNDIAL'


/*Ex 42*/
SELECT DISTINCT J.NOME, J.IDADE, T.NOME AS TIME
FROM JOGADOR J
INNER JOIN TIME T
ON J.IDTIME = T.ID

/*Ex 43*/
SELECT DISTINCT J.NOME, J.IDADE, T.NOME AS TIME
FROM JOGADOR J
LEFT JOIN TIME T
ON J.IDTIME = T.ID

/*Ex 44*/
SELECT DISTINCT J.NOME, J.IDADE, T.NOME AS TIME
FROM JOGADOR J
RIGHT JOIN TIME T
ON J.IDTIME = T.ID

/*Ex 45*/
SELECT DISTINCT J.NOME, J.IDADE, T.NOME AS TIME
FROM JOGADOR J
FULL JOIN TIME T
ON J.IDTIME = T.ID

/*Ex 46*/
SELECT SUM(J.SALARIO) AS [SALARIO TOTAL], T.NOME AS TIME
FROM JOGADOR J
INNER JOIN TIME T
ON J.IDTIME = T.ID
GROUP BY T.NOME

/*Ex 47*/
SELECT AVG(J.IDADE) AS [MEDIA IDADE], T.NOME AS TIME
FROM JOGADOR J
INNER JOIN TIME T
ON J.IDTIME = T.ID
GROUP BY T.NOME

/*Ex 48*/
SELECT AVG(J.IDADE) AS [MEDIA IDADE], T.NOME AS TIME
FROM JOGADOR J
INNER JOIN TIME T
ON J.IDTIME = T.ID
GROUP BY T.NOME
HAVING AVG(J.IDADE) > '30'

/*Ex 49*/
SELECT NOME, SALARIO
FROM JOGADOR 
WHERE SALARIO = (
	SELECT MAX(SALARIO)
	FROM JOGADOR)

/*Ex 50*/
SELECT NOME, SALARIO
FROM JOGADOR 
WHERE SALARIO = (
	SELECT MIN(SALARIO)
	FROM JOGADOR)

/*Ex 51*/
SELECT NOME, IDADE
FROM JOGADOR 
WHERE IDADE = (
	SELECT MAX(IDADE)
	FROM JOGADOR)

/*Ex 52*/
SELECT NOME, IDADE
FROM JOGADOR 
WHERE IDADE = (
	SELECT MIN(IDADE)
	FROM JOGADOR)

/*Ex 53*/
SELECT DISTINCT T.NOME, C.DESCRICAO AS CAMPEONATO, COUNT(C.DESCRICAO) AS TITULOS
FROM TIME T
INNER JOIN TITULO L
ON L.IDTIME = T.ID
INNER JOIN CAMPEONATO C
ON L.IDCAMPEONATO = C.ID
WHERE C.DESCRICAO IN ('Brasileirao')
GROUP BY T.NOME, C.DESCRICAO

/*Ex 54*/
SELECT DISTINCT T.NOME, C.DESCRICAO AS CAMPEONATO, COUNT(C.DESCRICAO) AS TITULOS
FROM TIME T
INNER JOIN TITULO L
ON L.IDTIME = T.ID
INNER JOIN CAMPEONATO C
ON L.IDCAMPEONATO = C.ID
WHERE C.DESCRICAO IN ('Libertadores')
GROUP BY T.NOME, C.DESCRICAO
ORDER BY T.NOME

/*Ex 55*/
SELECT DISTINCT T.NOME, C.DESCRICAO AS CAMPEONATO, COUNT(C.DESCRICAO) AS TITULOS
FROM TIME T
INNER JOIN TITULO L
ON L.IDTIME = T.ID
INNER JOIN CAMPEONATO C
ON L.IDCAMPEONATO = C.ID
WHERE C.DESCRICAO IN ('Mundial')
GROUP BY T.NOME, C.DESCRICAO
ORDER BY T.NOME

/*Ex 56*/
SELECT DISTINCT T.NOME, C.DESCRICAO AS CAMPEONATO, COUNT(C.DESCRICAO) AS TITULOS
FROM TIME T
INNER JOIN TITULO L
ON L.IDTIME = T.ID
INNER JOIN CAMPEONATO C
ON L.IDCAMPEONATO = C.ID
GROUP BY T.NOME, C.DESCRICAO
ORDER BY T.NOME, TITULOS DESC

