/*ex17*/
SELECT NOME, IDADE, SALARIO
FROM JOGADOR
WHERE IDADE BETWEEN 25 AND 30
ORDER BY NOME DESC

/*Ex18*/
SELECT NOME, IDADE, SALARIO
FROM JOGADOR
WHERE IDADE NOT BETWEEN 25 AND 30
ORDER BY NOME 

/*Ex19*/
SELECT COUNT(*) AS QteRegistros
FROM JOGADOR

/*Ex20*/
SELECT MIN(SALARIO) AS MenorSalario
FROM JOGADOR

/*Ex21*/
SELECT MAX(SALARIO) AS MaiorSalario
FROM JOGADOR

/*Ex22*/
SELECT AVG(SALARIO) AS MediaSalario
FROM JOGADOR

/*Ex23*/
SELECT IDADE
FROM JOGADOR
ORDER BY IDADE 

/*Ex24*/
SELECT DISTINCT(IDADE)
FROM JOGADOR
ORDER BY IDADE DESC 

/*Ex25*/
SELECT NOME, IDADE, SALARIO
FROM JOGADOR
WHERE NOME LIKE 'f%'

/*Ex26*/
SELECT NOME, IDADE, SALARIO
FROM JOGADOR
WHERE NOME LIKE '%a'

/*Ex27*/
SELECT NOME, IDADE, SALARIO
FROM JOGADOR
WHERE NOME LIKE '%ro%'

/*Ex28*/
SELECT NOME, DESCRICAO
FROM JOGADOR J
INNER JOIN POSICAO P
ON P.ID = J.IDPOSICAO

/*Ex29*/
SELECT NOME AS Goleiros, DESCRICAO
FROM JOGADOR J
INNER JOIN POSICAO P
ON P.ID = J.IDPOSICAO
WHERE DESCRICAO = 'Goleiro'

/*Ex30*/
SELECT NOME AS LateraisDireitos, DESCRICAO
FROM JOGADOR J
INNER JOIN POSICAO P
ON P.ID = J.IDPOSICAO
WHERE DESCRICAO = 'Lateral Direito'

/*Ex31*/
SELECT NOME AS LateraisEsquerdos, DESCRICAO
FROM JOGADOR J
INNER JOIN POSICAO P
ON P.ID = J.IDPOSICAO
WHERE DESCRICAO = 'Lateral Esquerdo'

/*Ex32*/
SELECT NOME AS Zagueiros, DESCRICAO
FROM JOGADOR J
INNER JOIN POSICAO P
ON P.ID = J.IDPOSICAO
WHERE DESCRICAO = 'Zagueiro'

/*Ex33*/
SELECT NOME AS Volantes, DESCRICAO
FROM JOGADOR J
INNER JOIN POSICAO P
ON P.ID = J.IDPOSICAO
WHERE DESCRICAO = 'Volante'

/*Ex34*/
SELECT NOME AS Meias, DESCRICAO
FROM JOGADOR J
INNER JOIN POSICAO P
ON P.ID = J.IDPOSICAO
WHERE DESCRICAO = 'Meia'

/*Ex35*/
SELECT NOME AS Atacantes, DESCRICAO
FROM JOGADOR J
INNER JOIN POSICAO P
ON P.ID = J.IDPOSICAO
WHERE DESCRICAO = 'Atacante'

/*Ex36*/
SELECT J.NOME AS Jogador, T.NOME AS Time
FROM JOGADOR J
INNER JOIN TIME T
ON T.ID = J.IDTIME

/*Ex37*/
SELECT J.NOME, J.IDADE, J.SALARIO, T.NOME AS Time
FROM JOGADOR J
INNER JOIN TIME T
ON T.ID = J.IDTIME
WHERE T.NOME = 'Flamengo'

/*Ex38*/
SELECT J.NOME, J.IDADE, J.SALARIO, T.NOME AS Time
FROM JOGADOR J
INNER JOIN TIME T
ON T.ID = J.IDTIME
WHERE T.NOME = 'Palmeiras'

/*Ex39*/
SELECT J.NOME, J.IDADE, J.SALARIO, P.DESCRICAO, T.NOME
FROM POSICAO P
INNER JOIN JOGADOR J
ON J.ID = P.ID
INNER JOIN TIME T
ON P.ID = T.ID

/*Ex40*/
SELECT DISTINCT T.NOME, C.DESCRICAO
FROM TIME T
INNER JOIN TITULO L
ON L.IDTIME = T.ID
INNER JOIN CAMPEONATO C
ON L.IDCAMPEONATO = C.ID
WHERE C.DESCRICAO = 'Brasileirao'

